services:
  server:
    image: node:22
    ports:
      - 3003:3003
    volumes:
      - ./code/server:/app
    working_dir: /app
    tty: true
  client:
    image: node:22
    ports:
      - 5173:5173 #port de developement
      - 4173:4173 #port de pre-production
      # 5173 c'est le port de vite (react)
    volumes:
      - ./code/client:/app
    working_dir: /app
    tty: true

